## ??????
#logging.level.com.alibaba.cloud.nacos=DEBUG
#logging.level.com.alibaba.nacos.client.config=DEBUG
#logging.level.org.springframework.cloud.bootstrap=DEBUG
#
## ???????
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n

coupon.user.name=zhangsan2
coupon.user.age=20
