spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/${segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/${segment}  # 注意：这里是 ${segment}

server:
  port: 88


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
    reactor.netty.http.client: TRACE
    com.alibaba.nacos.client: INFO
#spring:
#  spring:
#    application:
#      name: gulimall-gateway
##    datasource:
##      username: root
##      password: root
##      url: jdbc:mysql://8.159.145.116:3306/gulimall_ums
##      driver-class-name: com.mysql.cj.jdbc.Driver
#    cloud:
#      nacos:
#        discovery:
#          server-addr: 127.0.0.1:8848
#  #        enabled: true  # 启用Nacos，但注册由延迟注册器控制
#  #        register-enabled: false  # 禁用自动注册
#
#  server:
#    port: 88
#  cloud:
#    gateway:
#      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq
#        - id: admin_route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
#
### 前端项目，/api